allowBuilds:
  esbuild: true
minimumReleaseAgeExclude:
  - '@modelcontextprotocol/client@2.3.0'
  - '@modelcontextprotocol/core@2.3.0'
  - '@modelcontextprotocol/hono@2.0.2'
  - '@modelcontextprotocol/server@2.3.0'
